/*
(4)
CREATE THE TEST TABLES
*/

USE [CTPOC];
GO
IF OBJECT_ID('dbo.TestRecords1', 'U') IS NOT NULL
DROP TABLE dbo.TestRecords1;
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
SET ANSI_PADDING ON;
GO
CREATE TABLE [dbo].[TestRecords1]
([ID]          [INT] IDENTITY(1, 1) NOT NULL, 
 [FakeVarchar] [VARCHAR](255) NULL, 
 [FakeInt]     [INT] NULL, 
 [FakeDate]    [DATE] NULL, 
 PRIMARY KEY CLUSTERED([ID] ASC)
 WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY];
GO
SET ANSI_PADDING OFF;
GO
USE [CTPOC];
GO
IF OBJECT_ID('dbo.TestRecords2', 'U') IS NOT NULL
DROP TABLE dbo.TestRecords2;
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
SET ANSI_PADDING ON;
GO
CREATE TABLE [dbo].[TestRecords2]
([ID]          [INT] IDENTITY(1, 1) NOT NULL, 
 [FakeVarchar] [VARCHAR](255) NULL, 
 [FakeInt]     [INT] NULL, 
 [FakeDate]    [DATE] NULL, 
 PRIMARY KEY CLUSTERED([ID] ASC)
 WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY];
GO
SET ANSI_PADDING OFF;
GO
USE [CTPOC];
GO
IF OBJECT_ID('dbo.TestRecords3', 'U') IS NOT NULL
DROP TABLE dbo.TestRecords3;
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
SET ANSI_PADDING ON;
GO
CREATE TABLE [dbo].[TestRecords3]
([ID]          [INT] IDENTITY(1, 1) NOT NULL, 
 [FakeVarchar] [VARCHAR](255) NULL, 
 [FakeInt]     [INT] NULL, 
 [FakeDate]    [DATE] NULL, 
 PRIMARY KEY CLUSTERED([ID] ASC)
 WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY];
GO
SET ANSI_PADDING OFF;
GO
USE [CTPOC];
GO
IF OBJECT_ID('dbo.TestRecords4', 'U') IS NOT NULL
DROP TABLE dbo.TestRecords4;
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
SET ANSI_PADDING ON;
GO
CREATE TABLE [dbo].[TestRecords4]
([ID]          [INT] IDENTITY(1, 1) NOT NULL, 
 [FakeVarchar] [VARCHAR](255) NULL, 
 [FakeInt]     [INT] NULL, 
 [FakeDate]    [DATE] NULL, 
 PRIMARY KEY CLUSTERED([ID] ASC)
 WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY];
GO
SET ANSI_PADDING OFF;
GO
USE [CTPOC];
GO
IF OBJECT_ID('dbo.TestRecords5', 'U') IS NOT NULL
DROP TABLE dbo.TestRecords5;
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
SET ANSI_PADDING ON;
GO
CREATE TABLE [dbo].[TestRecords5]
([ID]          [INT] IDENTITY(1, 1) NOT NULL, 
 [FakeVarchar] [VARCHAR](255) NULL, 
 [FakeInt]     [INT] NULL, 
 [FakeDate]    [DATE] NULL, 
 PRIMARY KEY CLUSTERED([ID] ASC)
 WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY];
GO
SET ANSI_PADDING OFF;
GO
USE [CTPOC];
GO
IF OBJECT_ID('dbo.TestRecords1Dest', 'U') IS NOT NULL
DROP TABLE dbo.TestRecords1Dest;
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
SET ANSI_PADDING ON;
GO
CREATE TABLE [dbo].[TestRecords1Dest]
([DestID]      [INT] IDENTITY(1, 1) NOT NULL, 
 [ID]          [INT] NULL, 
 [FakeVarchar] [VARCHAR](255) NULL, 
 [FakeInt]     [INT] NULL, 
 [FakeDate]    [DATE] NULL, 
 PRIMARY KEY CLUSTERED([DestID] ASC)
 WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY];
GO
SET ANSI_PADDING OFF;
GO
USE [CTPOC];
GO
IF OBJECT_ID('dbo.TestRecords2Dest', 'U') IS NOT NULL
DROP TABLE dbo.TestRecords2Dest;
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
SET ANSI_PADDING ON;
GO
CREATE TABLE [dbo].[TestRecords2Dest]
([DestID]      [INT] IDENTITY(1, 1) NOT NULL, 
 [ID]          [INT] NULL, 
 [FakeVarchar] [VARCHAR](255) NULL, 
 [FakeInt]     [INT] NULL, 
 [FakeDate]    [DATE] NULL, 
 PRIMARY KEY CLUSTERED([DestID] ASC)
 WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY];
GO
SET ANSI_PADDING OFF;
GO
USE [CTPOC];
GO
IF OBJECT_ID('dbo.TestRecords3Dest', 'U') IS NOT NULL
DROP TABLE dbo.TestRecords3Dest;
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
SET ANSI_PADDING ON;
GO
CREATE TABLE [dbo].[TestRecords3Dest]
([DestID]      [INT] IDENTITY(1, 1) NOT NULL, 
 [ID]          [INT] NULL, 
 [FakeVarchar] [VARCHAR](255) NULL, 
 [FakeInt]     [INT] NULL, 
 [FakeDate]    [DATE] NULL, 
 PRIMARY KEY CLUSTERED([DestID] ASC)
 WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY];
GO
SET ANSI_PADDING OFF;
GO
USE [CTPOC];
GO
IF OBJECT_ID('dbo.TestRecords4Dest', 'U') IS NOT NULL
DROP TABLE dbo.TestRecords4Dest;
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
SET ANSI_PADDING ON;
GO
CREATE TABLE [dbo].[TestRecords4Dest]
([DestID]      [INT] IDENTITY(1, 1) NOT NULL, 
 [ID]          [INT] NULL, 
 [FakeVarchar] [VARCHAR](255) NULL, 
 [FakeInt]     [INT] NULL, 
 [FakeDate]    [DATE] NULL, 
 PRIMARY KEY CLUSTERED([DestID] ASC)
 WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY];
GO
SET ANSI_PADDING OFF;
GO
USE [CTPOC];
GO
IF OBJECT_ID('dbo.TestRecords5Dest', 'U') IS NOT NULL
DROP TABLE dbo.TestRecords5Dest;
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
SET ANSI_PADDING ON;
GO
CREATE TABLE [dbo].[TestRecords5Dest]
([DestID]      [INT] IDENTITY(1, 1) NOT NULL, 
 [ID]          [INT] NULL, 
 [FakeVarchar] [VARCHAR](255) NULL, 
 [FakeInt]     [INT] NULL, 
 [FakeDate]    [DATE] NULL, 
 PRIMARY KEY CLUSTERED([DestID] ASC)
 WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY];
GO
SET ANSI_PADDING OFF;
GO