/*
(4)
CREATE THE TEST TABLES
*/

USE [CTPOC];
GO
IF OBJECT_ID('dbo.TestRecords1', 'U') IS NOT NULL
DROP TABLE dbo.TestRecords1;
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
SET ANSI_PADDING ON;
GO
CREATE TABLE [dbo].[TestRecords1]
([ID]          [INT] IDENTITY(1, 1) NOT NULL, 
 [FakeVarchar] [VARCHAR](255) NULL, 
 [FakeInt]     [INT] NULL, 
 [FakeDate]    [DATE] NULL, 
 PRIMARY KEY CLUSTERED([ID] ASC)
 WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY];
GO
SET ANSI_PADDING OFF;
GO
USE [CTPOC];
GO
IF OBJECT_ID('dbo.TestRecords1Dest', 'U') IS NOT NULL
DROP TABLE dbo.TestRecords1Dest;
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
SET ANSI_PADDING ON;
GO
CREATE TABLE [dbo].[TestRecords1Dest]
([DestID]      [INT] IDENTITY(1, 1) NOT NULL, 
 [ID]          [INT] NULL, 
 [FakeVarchar] [VARCHAR](255) NULL, 
 [FakeInt]     [INT] NULL, 
 [FakeDate]    [DATE] NULL, 
 PRIMARY KEY CLUSTERED([DestID] ASC)
 WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY];
GO
SET ANSI_PADDING OFF;
GO

-- Enable CT at DB Level
ALTER DATABASE CTPOC SET CHANGE_TRACKING = ON(CHANGE_RETENTION = 2 DAYS, AUTO_CLEANUP = ON);

-- Enable CT at Table Level

USE CTPOC;
ALTER TABLE TestRecords1 ENABLE CHANGE_TRACKING
WITH(TRACK_COLUMNS_UPDATED = ON);

